
platform :ios, '9.0'

target 'HHYTV' do
  use_frameworks!

#pod 'Moya'
#pod 'Moya/RxSwift'
#pod 'SnapKit'
pod 'HandyJSON',:git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'dev_for_swift5.0'
#pod 'SwiftyJSON'

pod 'Kingfisher'
pod "Alamofire"

pod 'ProtocolBuffers-Swift'

end
